#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDataServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StockTrainer")]
	public partial class DBStockTrainerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertInsiderTrade(InsiderTrade instance);
    partial void UpdateInsiderTrade(InsiderTrade instance);
    partial void DeleteInsiderTrade(InsiderTrade instance);
    partial void InsertPortfolio(Portfolio instance);
    partial void UpdatePortfolio(Portfolio instance);
    partial void DeletePortfolio(Portfolio instance);
    partial void InsertStock(Stock instance);
    partial void UpdateStock(Stock instance);
    partial void DeleteStock(Stock instance);
    partial void InsertTransaction(Transaction instance);
    partial void UpdateTransaction(Transaction instance);
    partial void DeleteTransaction(Transaction instance);
    partial void InsertWatchStock(WatchStock instance);
    partial void UpdateWatchStock(WatchStock instance);
    partial void DeleteWatchStock(WatchStock instance);
    #endregion
		
		public DBStockTrainerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StockTrainerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBStockTrainerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStockTrainerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStockTrainerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBStockTrainerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<InsiderTrade> InsiderTrades
		{
			get
			{
				return this.GetTable<InsiderTrade>();
			}
		}
		
		public System.Data.Linq.Table<Portfolio> Portfolios
		{
			get
			{
				return this.GetTable<Portfolio>();
			}
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<Stock> Stocks
		{
			get
			{
				return this.GetTable<Stock>();
			}
		}
		
		public System.Data.Linq.Table<Transaction> Transactions
		{
			get
			{
				return this.GetTable<Transaction>();
			}
		}
		
		public System.Data.Linq.Table<WatchStock> WatchStocks
		{
			get
			{
				return this.GetTable<WatchStock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private double _Investment;
		
		private double _AvailableCash;
		
		private long _TotalTrans;
		
		private long _PositiveTrans;
		
		private long _NegativeTrans;
		
		private EntitySet<Portfolio> _Portfolios;
		
		private EntitySet<Transaction> _Transactions;
		
		private EntitySet<WatchStock> _WatchStocks;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnInvestmentChanging(double value);
    partial void OnInvestmentChanged();
    partial void OnAvailableCashChanging(double value);
    partial void OnAvailableCashChanged();
    partial void OnTotalTransChanging(long value);
    partial void OnTotalTransChanged();
    partial void OnPositiveTransChanging(long value);
    partial void OnPositiveTransChanged();
    partial void OnNegativeTransChanging(long value);
    partial void OnNegativeTransChanged();
    #endregion
		
		public Account()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Investment", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public double Investment
		{
			get
			{
				return this._Investment;
			}
			set
			{
				if ((this._Investment != value))
				{
					this.OnInvestmentChanging(value);
					this.SendPropertyChanging();
					this._Investment = value;
					this.SendPropertyChanged("Investment");
					this.OnInvestmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableCash", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public double AvailableCash
		{
			get
			{
				return this._AvailableCash;
			}
			set
			{
				if ((this._AvailableCash != value))
				{
					this.OnAvailableCashChanging(value);
					this.SendPropertyChanging();
					this._AvailableCash = value;
					this.SendPropertyChanged("AvailableCash");
					this.OnAvailableCashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTrans", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public long TotalTrans
		{
			get
			{
				return this._TotalTrans;
			}
			set
			{
				if ((this._TotalTrans != value))
				{
					this.OnTotalTransChanging(value);
					this.SendPropertyChanging();
					this._TotalTrans = value;
					this.SendPropertyChanged("TotalTrans");
					this.OnTotalTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositiveTrans", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public long PositiveTrans
		{
			get
			{
				return this._PositiveTrans;
			}
			set
			{
				if ((this._PositiveTrans != value))
				{
					this.OnPositiveTransChanging(value);
					this.SendPropertyChanging();
					this._PositiveTrans = value;
					this.SendPropertyChanged("PositiveTrans");
					this.OnPositiveTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NegativeTrans", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public long NegativeTrans
		{
			get
			{
				return this._NegativeTrans;
			}
			set
			{
				if ((this._NegativeTrans != value))
				{
					this.OnNegativeTransChanging(value);
					this.SendPropertyChanging();
					this._NegativeTrans = value;
					this.SendPropertyChanged("NegativeTrans");
					this.OnNegativeTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Portfolio", Storage="_Portfolios", ThisKey="Username", OtherKey="Username")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8, EmitDefaultValue=false)]
		public EntitySet<Portfolio> Portfolios
		{
			get
			{
				if ((this.serializing 
							&& (this._Portfolios.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Portfolios;
			}
			set
			{
				this._Portfolios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Transaction", Storage="_Transactions", ThisKey="Username", OtherKey="Username")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9, EmitDefaultValue=false)]
		public EntitySet<Transaction> Transactions
		{
			get
			{
				if ((this.serializing 
							&& (this._Transactions.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Transactions;
			}
			set
			{
				this._Transactions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_WatchStock", Storage="_WatchStocks", ThisKey="Username", OtherKey="Username")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10, EmitDefaultValue=false)]
		public EntitySet<WatchStock> WatchStocks
		{
			get
			{
				if ((this.serializing 
							&& (this._WatchStocks.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._WatchStocks;
			}
			set
			{
				this._WatchStocks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Portfolios(Portfolio entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Portfolios(Portfolio entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_WatchStocks(WatchStock entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_WatchStocks(WatchStock entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void Initialize()
		{
			this._Portfolios = new EntitySet<Portfolio>(new Action<Portfolio>(this.attach_Portfolios), new Action<Portfolio>(this.detach_Portfolios));
			this._Transactions = new EntitySet<Transaction>(new Action<Transaction>(this.attach_Transactions), new Action<Transaction>(this.detach_Transactions));
			this._WatchStocks = new EntitySet<WatchStock>(new Action<WatchStock>(this.attach_WatchStocks), new Action<WatchStock>(this.detach_WatchStocks));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InsiderTrades")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class InsiderTrade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _InsiderTradeID;
		
		private string _Ticker;
		
		private string _InsiderDetail;
		
		private string _CompanyName;
		
		private string _Type;
		
		private long _Quantity;
		
		private double _Price;
		
		private double _Total;
		
		private System.DateTime _Time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInsiderTradeIDChanging(long value);
    partial void OnInsiderTradeIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnInsiderDetailChanging(string value);
    partial void OnInsiderDetailChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnQuantityChanging(long value);
    partial void OnQuantityChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnTotalChanging(double value);
    partial void OnTotalChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    #endregion
		
		public InsiderTrade()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsiderTradeID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public long InsiderTradeID
		{
			get
			{
				return this._InsiderTradeID;
			}
			set
			{
				if ((this._InsiderTradeID != value))
				{
					this.OnInsiderTradeIDChanging(value);
					this.SendPropertyChanging();
					this._InsiderTradeID = value;
					this.SendPropertyChanged("InsiderTradeID");
					this.OnInsiderTradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsiderDetail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string InsiderDetail
		{
			get
			{
				return this._InsiderDetail;
			}
			set
			{
				if ((this._InsiderDetail != value))
				{
					this.OnInsiderDetailChanging(value);
					this.SendPropertyChanging();
					this._InsiderDetail = value;
					this.SendPropertyChanged("InsiderDetail");
					this.OnInsiderDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public long Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public double Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Portfolio")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Portfolio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Ticker;
		
		private double _Cost;
		
		private long _NumStocks;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<Stock> _Stock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnCostChanging(double value);
    partial void OnCostChanged();
    partial void OnNumStocksChanging(long value);
    partial void OnNumStocksChanged();
    #endregion
		
		public Portfolio()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					if (this._Stock.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public double Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumStocks", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public long NumStocks
		{
			get
			{
				return this._NumStocks;
			}
			set
			{
				if ((this._NumStocks != value))
				{
					this.OnNumStocksChanging(value);
					this.SendPropertyChanging();
					this._NumStocks = value;
					this.SendPropertyChanged("NumStocks");
					this.OnNumStocksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Portfolio", Storage="_Account", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Portfolios.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Portfolios.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stock_Portfolio", Storage="_Stock", ThisKey="Ticker", OtherKey="Ticker", IsForeignKey=true)]
		public Stock Stock
		{
			get
			{
				return this._Stock.Entity;
			}
			set
			{
				Stock previousValue = this._Stock.Entity;
				if (((previousValue != value) 
							|| (this._Stock.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stock.Entity = null;
						previousValue.Portfolios.Remove(this);
					}
					this._Stock.Entity = value;
					if ((value != null))
					{
						value.Portfolios.Add(this);
						this._Ticker = value.Ticker;
					}
					else
					{
						this._Ticker = default(string);
					}
					this.SendPropertyChanged("Stock");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Account = default(EntityRef<Account>);
			this._Stock = default(EntityRef<Stock>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Setting
	{
		
		private int _AutoUpdateTimer;
		
		private bool _EnforceMarketTimings;
		
		public Setting()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoUpdateTimer", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int AutoUpdateTimer
		{
			get
			{
				return this._AutoUpdateTimer;
			}
			set
			{
				if ((this._AutoUpdateTimer != value))
				{
					this._AutoUpdateTimer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnforceMarketTimings", DbType="Bit NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public bool EnforceMarketTimings
		{
			get
			{
				return this._EnforceMarketTimings;
			}
			set
			{
				if ((this._EnforceMarketTimings != value))
				{
					this._EnforceMarketTimings = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stock")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ticker;
		
		private string _EquityName;
		
		private double _Price;
		
		private double _PrevClosePrice;
		
		private double _HighPrice;
		
		private double _LowPrice;
		
		private double _OpenPrice;
		
		private double _Volume;
		
		private double _Change;
		
		private double _MarketCap;
		
		private double @__52_week_High;
		
		private double @__52_week_Low;
		
		private double _AskPrice;
		
		private double _BidPrice;
		
		private double _AskSize;
		
		private double _BidSize;
		
		private double @__1_Year_Return;
		
		private double _Beta;
		
		private double _PE_Ratio;
		
		private double _Dividend;
		
		private double _DividendPercent;
		
		private int _UpdateChecker;
		
		private EntitySet<Portfolio> _Portfolios;
		
		private EntitySet<WatchStock> _WatchStocks;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnEquityNameChanging(string value);
    partial void OnEquityNameChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnPrevClosePriceChanging(double value);
    partial void OnPrevClosePriceChanged();
    partial void OnHighPriceChanging(double value);
    partial void OnHighPriceChanged();
    partial void OnLowPriceChanging(double value);
    partial void OnLowPriceChanged();
    partial void OnOpenPriceChanging(double value);
    partial void OnOpenPriceChanged();
    partial void OnVolumeChanging(double value);
    partial void OnVolumeChanged();
    partial void OnChangeChanging(double value);
    partial void OnChangeChanged();
    partial void OnMarketCapChanging(double value);
    partial void OnMarketCapChanged();
    partial void On_52_week_HighChanging(double value);
    partial void On_52_week_HighChanged();
    partial void On_52_week_LowChanging(double value);
    partial void On_52_week_LowChanged();
    partial void OnAskPriceChanging(double value);
    partial void OnAskPriceChanged();
    partial void OnBidPriceChanging(double value);
    partial void OnBidPriceChanged();
    partial void OnAskSizeChanging(double value);
    partial void OnAskSizeChanged();
    partial void OnBidSizeChanging(double value);
    partial void OnBidSizeChanged();
    partial void On_1_Year_ReturnChanging(double value);
    partial void On_1_Year_ReturnChanged();
    partial void OnBetaChanging(double value);
    partial void OnBetaChanged();
    partial void OnPE_RatioChanging(double value);
    partial void OnPE_RatioChanged();
    partial void OnDividendChanging(double value);
    partial void OnDividendChanged();
    partial void OnDividendPercentChanging(double value);
    partial void OnDividendPercentChanged();
    partial void OnUpdateCheckerChanging(int value);
    partial void OnUpdateCheckerChanged();
    #endregion
		
		public Stock()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquityName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string EquityName
		{
			get
			{
				return this._EquityName;
			}
			set
			{
				if ((this._EquityName != value))
				{
					this.OnEquityNameChanging(value);
					this.SendPropertyChanging();
					this._EquityName = value;
					this.SendPropertyChanged("EquityName");
					this.OnEquityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrevClosePrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public double PrevClosePrice
		{
			get
			{
				return this._PrevClosePrice;
			}
			set
			{
				if ((this._PrevClosePrice != value))
				{
					this.OnPrevClosePriceChanging(value);
					this.SendPropertyChanging();
					this._PrevClosePrice = value;
					this.SendPropertyChanged("PrevClosePrice");
					this.OnPrevClosePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public double HighPrice
		{
			get
			{
				return this._HighPrice;
			}
			set
			{
				if ((this._HighPrice != value))
				{
					this.OnHighPriceChanging(value);
					this.SendPropertyChanging();
					this._HighPrice = value;
					this.SendPropertyChanged("HighPrice");
					this.OnHighPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public double LowPrice
		{
			get
			{
				return this._LowPrice;
			}
			set
			{
				if ((this._LowPrice != value))
				{
					this.OnLowPriceChanging(value);
					this.SendPropertyChanging();
					this._LowPrice = value;
					this.SendPropertyChanged("LowPrice");
					this.OnLowPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public double OpenPrice
		{
			get
			{
				return this._OpenPrice;
			}
			set
			{
				if ((this._OpenPrice != value))
				{
					this.OnOpenPriceChanging(value);
					this.SendPropertyChanging();
					this._OpenPrice = value;
					this.SendPropertyChanged("OpenPrice");
					this.OnOpenPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public double Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public double Change
		{
			get
			{
				return this._Change;
			}
			set
			{
				if ((this._Change != value))
				{
					this.OnChangeChanging(value);
					this.SendPropertyChanging();
					this._Change = value;
					this.SendPropertyChanged("Change");
					this.OnChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public double MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[52-week_High]", Storage="__52_week_High", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public double _52_week_High
		{
			get
			{
				return this.@__52_week_High;
			}
			set
			{
				if ((this.@__52_week_High != value))
				{
					this.On_52_week_HighChanging(value);
					this.SendPropertyChanging();
					this.@__52_week_High = value;
					this.SendPropertyChanged("_52_week_High");
					this.On_52_week_HighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[52-week_Low]", Storage="__52_week_Low", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public double _52_week_Low
		{
			get
			{
				return this.@__52_week_Low;
			}
			set
			{
				if ((this.@__52_week_Low != value))
				{
					this.On_52_week_LowChanging(value);
					this.SendPropertyChanging();
					this.@__52_week_Low = value;
					this.SendPropertyChanged("_52_week_Low");
					this.On_52_week_LowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AskPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public double AskPrice
		{
			get
			{
				return this._AskPrice;
			}
			set
			{
				if ((this._AskPrice != value))
				{
					this.OnAskPriceChanging(value);
					this.SendPropertyChanging();
					this._AskPrice = value;
					this.SendPropertyChanged("AskPrice");
					this.OnAskPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public double BidPrice
		{
			get
			{
				return this._BidPrice;
			}
			set
			{
				if ((this._BidPrice != value))
				{
					this.OnBidPriceChanging(value);
					this.SendPropertyChanging();
					this._BidPrice = value;
					this.SendPropertyChanged("BidPrice");
					this.OnBidPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AskSize", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public double AskSize
		{
			get
			{
				return this._AskSize;
			}
			set
			{
				if ((this._AskSize != value))
				{
					this.OnAskSizeChanging(value);
					this.SendPropertyChanging();
					this._AskSize = value;
					this.SendPropertyChanged("AskSize");
					this.OnAskSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidSize", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public double BidSize
		{
			get
			{
				return this._BidSize;
			}
			set
			{
				if ((this._BidSize != value))
				{
					this.OnBidSizeChanging(value);
					this.SendPropertyChanging();
					this._BidSize = value;
					this.SendPropertyChanged("BidSize");
					this.OnBidSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1-Year_Return]", Storage="__1_Year_Return", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public double _1_Year_Return
		{
			get
			{
				return this.@__1_Year_Return;
			}
			set
			{
				if ((this.@__1_Year_Return != value))
				{
					this.On_1_Year_ReturnChanging(value);
					this.SendPropertyChanging();
					this.@__1_Year_Return = value;
					this.SendPropertyChanged("_1_Year_Return");
					this.On_1_Year_ReturnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beta", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public double Beta
		{
			get
			{
				return this._Beta;
			}
			set
			{
				if ((this._Beta != value))
				{
					this.OnBetaChanging(value);
					this.SendPropertyChanging();
					this._Beta = value;
					this.SendPropertyChanged("Beta");
					this.OnBetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PE_Ratio", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public double PE_Ratio
		{
			get
			{
				return this._PE_Ratio;
			}
			set
			{
				if ((this._PE_Ratio != value))
				{
					this.OnPE_RatioChanging(value);
					this.SendPropertyChanging();
					this._PE_Ratio = value;
					this.SendPropertyChanged("PE_Ratio");
					this.OnPE_RatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dividend", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public double Dividend
		{
			get
			{
				return this._Dividend;
			}
			set
			{
				if ((this._Dividend != value))
				{
					this.OnDividendChanging(value);
					this.SendPropertyChanging();
					this._Dividend = value;
					this.SendPropertyChanged("Dividend");
					this.OnDividendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DividendPercent", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public double DividendPercent
		{
			get
			{
				return this._DividendPercent;
			}
			set
			{
				if ((this._DividendPercent != value))
				{
					this.OnDividendPercentChanging(value);
					this.SendPropertyChanging();
					this._DividendPercent = value;
					this.SendPropertyChanged("DividendPercent");
					this.OnDividendPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateChecker", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public int UpdateChecker
		{
			get
			{
				return this._UpdateChecker;
			}
			set
			{
				if ((this._UpdateChecker != value))
				{
					this.OnUpdateCheckerChanging(value);
					this.SendPropertyChanging();
					this._UpdateChecker = value;
					this.SendPropertyChanged("UpdateChecker");
					this.OnUpdateCheckerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stock_Portfolio", Storage="_Portfolios", ThisKey="Ticker", OtherKey="Ticker")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23, EmitDefaultValue=false)]
		public EntitySet<Portfolio> Portfolios
		{
			get
			{
				if ((this.serializing 
							&& (this._Portfolios.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Portfolios;
			}
			set
			{
				this._Portfolios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stock_WatchStock", Storage="_WatchStocks", ThisKey="Ticker", OtherKey="Ticker")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24, EmitDefaultValue=false)]
		public EntitySet<WatchStock> WatchStocks
		{
			get
			{
				if ((this.serializing 
							&& (this._WatchStocks.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._WatchStocks;
			}
			set
			{
				this._WatchStocks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Portfolios(Portfolio entity)
		{
			this.SendPropertyChanging();
			entity.Stock = this;
		}
		
		private void detach_Portfolios(Portfolio entity)
		{
			this.SendPropertyChanging();
			entity.Stock = null;
		}
		
		private void attach_WatchStocks(WatchStock entity)
		{
			this.SendPropertyChanging();
			entity.Stock = this;
		}
		
		private void detach_WatchStocks(WatchStock entity)
		{
			this.SendPropertyChanging();
			entity.Stock = null;
		}
		
		private void Initialize()
		{
			this._Portfolios = new EntitySet<Portfolio>(new Action<Portfolio>(this.attach_Portfolios), new Action<Portfolio>(this.detach_Portfolios));
			this._WatchStocks = new EntitySet<WatchStock>(new Action<WatchStock>(this.attach_WatchStocks), new Action<WatchStock>(this.detach_WatchStocks));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transactions")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _TransactionID;
		
		private string _Username;
		
		private string _Ticker;
		
		private string _EquityName;
		
		private System.DateTime _Date;
		
		private string _Type;
		
		private long _NumStocks;
		
		private double _Price;
		
		private double _AvgBuyPrice;
		
		private System.Nullable<double> _GainLossMoney;
		
		private System.Nullable<double> _GainLossPercent;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionIDChanging(long value);
    partial void OnTransactionIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnEquityNameChanging(string value);
    partial void OnEquityNameChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnNumStocksChanging(long value);
    partial void OnNumStocksChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnAvgBuyPriceChanging(double value);
    partial void OnAvgBuyPriceChanged();
    partial void OnGainLossMoneyChanging(System.Nullable<double> value);
    partial void OnGainLossMoneyChanged();
    partial void OnGainLossPercentChanging(System.Nullable<double> value);
    partial void OnGainLossPercentChanged();
    #endregion
		
		public Transaction()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public long TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquityName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string EquityName
		{
			get
			{
				return this._EquityName;
			}
			set
			{
				if ((this._EquityName != value))
				{
					this.OnEquityNameChanging(value);
					this.SendPropertyChanging();
					this._EquityName = value;
					this.SendPropertyChanged("EquityName");
					this.OnEquityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumStocks", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public long NumStocks
		{
			get
			{
				return this._NumStocks;
			}
			set
			{
				if ((this._NumStocks != value))
				{
					this.OnNumStocksChanging(value);
					this.SendPropertyChanging();
					this._NumStocks = value;
					this.SendPropertyChanged("NumStocks");
					this.OnNumStocksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuyPrice", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public double AvgBuyPrice
		{
			get
			{
				return this._AvgBuyPrice;
			}
			set
			{
				if ((this._AvgBuyPrice != value))
				{
					this.OnAvgBuyPriceChanging(value);
					this.SendPropertyChanging();
					this._AvgBuyPrice = value;
					this.SendPropertyChanged("AvgBuyPrice");
					this.OnAvgBuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GainLossMoney", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<double> GainLossMoney
		{
			get
			{
				return this._GainLossMoney;
			}
			set
			{
				if ((this._GainLossMoney != value))
				{
					this.OnGainLossMoneyChanging(value);
					this.SendPropertyChanging();
					this._GainLossMoney = value;
					this.SendPropertyChanged("GainLossMoney");
					this.OnGainLossMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GainLossPercent", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<double> GainLossPercent
		{
			get
			{
				return this._GainLossPercent;
			}
			set
			{
				if ((this._GainLossPercent != value))
				{
					this.OnGainLossPercentChanging(value);
					this.SendPropertyChanging();
					this._GainLossPercent = value;
					this.SendPropertyChanged("GainLossPercent");
					this.OnGainLossPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Transaction", Storage="_Account", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Transactions.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Transactions.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WatchStock")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class WatchStock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Ticker;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<Stock> _Stock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    #endregion
		
		public WatchStock()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					if (this._Stock.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_WatchStock", Storage="_Account", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.WatchStocks.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.WatchStocks.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stock_WatchStock", Storage="_Stock", ThisKey="Ticker", OtherKey="Ticker", IsForeignKey=true)]
		public Stock Stock
		{
			get
			{
				return this._Stock.Entity;
			}
			set
			{
				Stock previousValue = this._Stock.Entity;
				if (((previousValue != value) 
							|| (this._Stock.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stock.Entity = null;
						previousValue.WatchStocks.Remove(this);
					}
					this._Stock.Entity = value;
					if ((value != null))
					{
						value.WatchStocks.Add(this);
						this._Ticker = value.Ticker;
					}
					else
					{
						this._Ticker = default(string);
					}
					this.SendPropertyChanged("Stock");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Account = default(EntityRef<Account>);
			this._Stock = default(EntityRef<Stock>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
