<?xml version="1.0" encoding="utf-8"?><Database Name="StockTrainer" Class="DBStockTrainerDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=StockTrainer.mssql.somee.com;Initial Catalog=StockTrainer;Persist Security Info=False;User ID=lmtri1995_SQLLogin_1;Packet Size=4096;Workstation ID=StockTrainer.mssql.somee.com" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StockTrainerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstSecurityQuestion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstSecurityAnswer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SecondSecurityQuestion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SecondSecurityAnswer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartingInvestment" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="AvailableCash" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalTrans" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PositiveTrans" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NegativeTrans" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Account_Portfolio" Member="Portfolios" ThisKey="Username" OtherKey="Username" Type="Portfolio" />
      <Association Name="Account_Transaction" Member="Transactions" ThisKey="Username" OtherKey="Username" Type="Transaction" />
      <Association Name="Account_WatchStock" Member="WatchStocks" ThisKey="Username" OtherKey="Username" Type="WatchStock" />
    </Type>
  </Table>
  <Table Name="dbo.History" Member="Histories">
    <Type Name="History">
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HistoryPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Association Name="Stock_History" Member="Stock" ThisKey="Ticker" OtherKey="Ticker" Type="Stock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InsiderTrade" Member="InsiderTrades">
    <Type Name="InsiderTrade">
      <Column Name="InsiderTradeID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InsiderNameAndDetails" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Portfolio" Member="Portfolios">
    <Type Name="Portfolio">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="NumStocks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Account_Portfolio" Member="Account" ThisKey="Username" OtherKey="Username" Type="Account" IsForeignKey="true" />
      <Association Name="Stock_Portfolio" Member="Stock" ThisKey="Ticker" OtherKey="Ticker" Type="Stock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="AutoUpdateTimer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnforceMarketTimings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EquityName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="PrevClosePrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="HighPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="LowPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="OpenPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Change" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="MarketCap" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="[52-week_High]" Member="_52_week_High" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="[52-week_Low]" Member="_52_week_Low" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="AskPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="BidPrice" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="AskSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BidSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UpdateChecker" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Stock_History" Member="Histories" ThisKey="Ticker" OtherKey="Ticker" Type="History" />
      <Association Name="Stock_Portfolio" Member="Portfolios" ThisKey="Ticker" OtherKey="Ticker" Type="Portfolio" />
      <Association Name="Stock_WatchStock" Member="WatchStocks" ThisKey="Ticker" OtherKey="Ticker" Type="WatchStock" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EquityName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NumStocks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(20,2) NOT NULL" CanBeNull="false" />
      <Column Name="GainLossMoney" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="GainLossPercent" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Association Name="Account_Transaction" Member="Account" ThisKey="Username" OtherKey="Username" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WatchStock" Member="WatchStocks">
    <Type Name="WatchStock">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Account_WatchStock" Member="Account" ThisKey="Username" OtherKey="Username" Type="Account" IsForeignKey="true" />
      <Association Name="Stock_WatchStock" Member="Stock" ThisKey="Ticker" OtherKey="Ticker" Type="Stock" IsForeignKey="true" />
    </Type>
  </Table>
</Database>